### ISSUE TITLE
KeyError: 'name' while generating markdown files

### ISSUE THREAD

**Issue by SpyrexDE** [GDQuest/gdscript-docs-maker#95]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
I followed the documentation on the readme to setup the docs-maker but it gives me an error while generating the markdownfiles.
```

$ git clone https://github.com/GDQuest/gdscript-docs-maker.git
Cloning into 'gdscript-docs-maker'...
$ mkdir -p documentation/api-reference
$ cd gdscript-docs-maker/
$ ./generate_reference ../code/game_dir_containg_the_godot.project_file -o ../documentation/api-reference
Checking parameters
Copying collectors to project directory
Generating reference json data...
Done.
Generating markdown files in ../documentation/api-reference
Error running gdscript_docs_maker. This is the log:
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/gdscript_docs_maker/__main__.py", line 74, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/gdscript_docs_maker/__main__.py", line 35, in main
    project_info: ProjectInfo = ProjectInfo.from_dict(data)
  File "/usr/local/lib/python3.9/dist-packages/gdscript_docs_maker/gdscript_objects.py", line 93, in from_dict
    return ProjectInfo(data["name"], data["description"], data["version"])
KeyError: 'name'

```
This also happens when run as root.
Im on Debian GNU/Linux 11 and the project is using Godot 4.2

**Comment by raldone01** [comment]
`4.1.3` is the latest version I got to work.
I changed the first line in the Dockerfile to `FROM docker.io/barichello/godot-ci:4.1.3`.
All later version fail.
I think it may be related to https://github.com/abarichello/godot-ci/issues/127.

Another issue is with:
https://github.com/GDQuest/gdscript-docs-maker/blob/07cb0d8f0af6da745260d7bfabfc475504c413f1/godot-scripts/CollectorGd4.gd#L92
The singleton seems to not be available at `_init` time anymore. See https://github.com/godotengine/godot/issues/86132.

Also I ran the [main loop example](https://docs.godotengine.org/en/stable/classes/class_mainloop.html) and the `_process` function does not work with `v4.2.1`.

**Comment by SpyrexDE** [comment]
Seems like Godot 4 is now officially not supported anymore. Are there any plans on porting it? @NathanLovato

**Comment by NathanLovato** [comment]
No, I don't have time. If someone would like to maintain this for Godot 4 that'd be very much welcome, but I won't be able to do it.
